-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Plexus Sentinel", {
	[1218625] = "blue",
	[1218668] = "blue",
	[1219223] = "blue",
	[1219248] = "blue",
	[1219263] = {"blue","purple"},
	[1219354] = "blue",
	[1219450] = {"blue","yellow"},
	[1219471] = "blue",
	[1219607] = {"blue","orange"},
	[1220679] = "blue",
	[1227794] = "blue",
	[1233110] = {"blue","purple"},
	[1234733] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("Plexus Sentinel", {
	[1218625] = "warning",
	[1218668] = "underyou",
	[1219223] = "underyou",
	[1219248] = "underyou",
	[1219263] = {"alarm","warning"},
	[1219354] = "underyou",
	[1219450] = "warning",
	[1219471] = "underyou",
	[1219607] = {"alert","warning"},
	[1220679] = "info",
	[1227794] = "underyou",
	[1233110] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Loom'ithar", {
	[1226311] = {"blue","cyan"},
	[1226366] = "blue",
	[1226395] = "red",
	[1226721] = "blue",
	[1227226] = "purple",
	[1227782] = "yellow",
	[1237212] = {"blue","purple"},
	[1237272] = "orange",
	[1238502] = "green",
	[1243771] = "blue",
	[1246921] = "yellow",
	[1247029] = "red",
	[1247045] = "blue",
	["stages"] = "green",
})

BigWigs:AddSounds("Loom'ithar", {
	[1226311] = "warning",
	[1226366] = "underyou",
	[1226395] = "warning",
	[1226721] = "warning",
	[1227226] = "warning",
	[1227782] = "alert",
	[1237212] = {"alarm","alert","warning"},
	[1237272] = "alert",
	[1238502] = "info",
	[1243771] = "underyou",
	[1246921] = "long",
	[1247045] = {"alarm","info"},
	["stages"] = "long",
})

BigWigs:AddColors("Soulbinder Naazindhri", {
	[1223859] = "orange",
	[1225582] = "cyan",
	[1225616] = {"blue","orange"},
	[1226827] = "blue",
	[1227048] = "blue",
	[1227052] = {"blue","orange"},
	[1227276] = {"blue","yellow"},
	[1241100] = {"blue","purple"},
	[1242086] = "blue",
})

BigWigs:AddSounds("Soulbinder Naazindhri", {
	[1223859] = "warning",
	[1225582] = "long",
	[1225616] = "warning",
	[1226827] = "alarm",
	[1227048] = "warning",
	[1227052] = "alarm",
	[1227276] = "warning",
	[1241100] = {"alarm","warning"},
	[1242086] = "underyou",
})

BigWigs:AddColors("Forgeweaver Araz", {
	[1227631] = "red",
	[1228188] = {"blue","cyan"},
	[1228214] = {"blue","yellow"},
	[1228216] = {"blue","purple"},
	[1228219] = "blue",
	[1228502] = {"blue","purple"},
	[1231720] = "cyan",
	[1232221] = "orange",
	[1232412] = "blue",
	[1232590] = "orange",
	[1233074] = "blue",
	[1233415] = {"blue","red"},
	[1234328] = "yellow",
	[1236207] = "blue",
	[1238266] = {"blue","purple"},
	[1240437] = "blue",
	[1240705] = "blue",
	[1243641] = "blue",
	[1243901] = {"blue","yellow"},
	[1248009] = "yellow",
	[1248171] = "orange",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Forgeweaver Araz", {
	[1227631] = "warning",
	[1228188] = "warning",
	[1228214] = "warning",
	[1228216] = "warning",
	[1228219] = "alarm",
	[1228502] = {"alarm","warning"},
	[1231720] = "long",
	[1232221] = "warning",
	[1232412] = "underyou",
	[1232590] = "alarm",
	[1233074] = "underyou",
	[1233415] = "long",
	[1234328] = "alert",
	[1236207] = "alarm",
	[1238266] = "alarm",
	[1240705] = "alarm",
	[1243641] = "alarm",
	[1243901] = {"info","warning"},
	[1248009] = "alert",
	[1248171] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("The Soul Hunters", {
	[1218103] = "purple",
	[1221490] = "blue",
	[1222232] = {"blue","green"},
	[1222310] = "blue",
	[1225130] = {"blue","purple"},
	[1226493] = "blue",
	[1227355] = "cyan",
	[1227685] = "blue",
	[1227809] = {"blue","orange"},
	[1233105] = {"blue","green"},
	[1233381] = "blue",
	[1233672] = "red",
	[1233968] = "blue",
	[1235045] = "blue",
	[1240891] = "yellow",
	[1241306] = "red",
	[1241833] = "purple",
	[1241946] = {"blue","green"},
	[1242259] = "yellow",
	[1242284] = "green",
	[1242304] = "red",
	[1245726] = "cyan",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("The Soul Hunters", {
	[1221490] = "alarm",
	[1222232] = {"alarm","info"},
	[1222310] = "warning",
	[1225130] = "alarm",
	[1226493] = "info",
	[1227355] = "info",
	[1227685] = "underyou",
	[1227809] = {"long","warning"},
	[1233105] = {"alarm","info"},
	[1233381] = "alarm",
	[1233672] = "warning",
	[1233968] = "underyou",
	[1235045] = "underyou",
	[1240891] = "warning",
	[1241306] = "alert",
	[1241833] = "alarm",
	[1241946] = {"alarm","info"},
	[1242259] = "alarm",
	[1242284] = "info",
	[1242304] = "warning",
	[1245726] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Fractillus", {
	[1224414] = "blue",
	[1225673] = "red",
	[1227373] = {"blue","cyan"},
	[1227378] = "blue",
	[1231871] = {"blue","purple"},
	[1232760] = "blue",
	[1233416] = {"blue","orange"},
	[1247424] = "blue",
})

BigWigs:AddSounds("Fractillus", {
	[1224414] = "warning",
	[1225673] = "warning",
	[1227373] = {"alarm","long"},
	[1227378] = "alarm",
	[1231871] = {"alarm","alert","warning"},
	[1233416] = "warning",
	[1247424] = "warning",
})

BigWigs:AddColors("Nexus-King Salhadaar", {
})

BigWigs:AddSounds("Nexus-King Salhadaar", {
})

BigWigs:AddColors("Dimensius, the All-Devouring", {
})

BigWigs:AddSounds("Dimensius, the All-Devouring", {
})
