-- Default locale
local ADDON_NAME, PRIVATE_TABLE = ...

if GetLocale() ~= "deDE" then
	return
end

local L = PRIVATE_TABLE.L

L["${n} seconds"] = "${n} Sekunden"
L["(Automatically in category)"] = "(Automatisch in Kategorie)"
L["Active Addons"] = "Aktive Addons"
L["Add search results to category"] = "Suchergebnisse zu Kategorie hinzufügen"
L["AddOn binary search"] = "Addon Binary-Suche"
L["Addons being modified"] = "Modifizierte Addons"
L["Addons being modified in this session"] = "In dieser Sitzung modifizierte Addons"
L["Addons enabled and loaded, or ready to be loaded on demand."] = "Aktive und geladene Addons (oder bereit bei Bedarf geladen zu werden)"
L["Addons not in any category. It will be taken into account if you are viewing or not auto-generated categories."] = "Addons in keiner Kategorie. Es wird berücksichtigt ob auto-generierte Kategorien aktiviet oder deaktiviert sind."
L["AddOns Total Memory"] = "Speicher aller Addons"
L["AddOns: "] = "Addons:"
L["Also disable Simple Addon Manager?"] = "Soll 'Simple Addon Manager' auch deaktiviert werden?"
--[[Translation missing --]]
L["Are you sure you want to remove all automatic character profiles?"] = "Are you sure you want to remove all automatic character profiles?"
--[[Translation missing --]]
L["Arena"] = "Arena"
L["Author"] = "Autor"
L["Author: "] = "Autor:"
L["Autofocus searchbar when opening the UI"] = "Suchleiste beim öffnen des UI fokussieren"
L["Automatically added:"] = "Automatisch hinzugefügt:"
--[[Translation missing --]]
L["Average"] = "Average"
--[[Translation missing --]]
L["Average CPU: "] = "Average CPU: "
L["Be careful with this option, enabling/disabling Blizzard Addons might have unintended consequences!"] = "Vorsicht! Aktivieren und Deaktivieren von Blizzard Addons kann ungewünschte Folgen haben!"
L["Categories"] = "Kategorien"
--[[Translation missing --]]
L["Categories: "] = "Categories: "
L["Category created from addons metadata"] = "Aus Addon-Metadaten erstellte Kategorie"
L["Category Options"] = "Kategorieoptionen"
L["Characters"] = "Charaktere"
--[[Translation missing --]]
L["Characters: "] = "Characters: "
L["Circular dependency detected!"] = "Zirkuläre Abhängigkeit festgestellt!"
--[[Translation missing --]]
L["Clear list"] = "Clear list"
L["Collapse all"] = "Alle einklappen"
--[[Translation missing --]]
L["CPU Usage"] = "CPU Usage"
--[[Translation missing --]]
L["CPU: "] = "CPU: "
L["Create new profile"] = "Neues Profil erstellen"
--[[Translation missing --]]
L["Current"] = "Current"
L["Currently Disabled Addons"] = "Inaktive Addons"
L["Currently Enabled Addons"] = "Aktive Addons"
L["Delete"] = "Löschen"
L["Delete category '${category}'?"] = "Kategorie '${category}' löschen?"
L["Delete the profile '${profile}'?"] = "Profil '${profile}' löschen?"
--[[Translation missing --]]
L["Disable Addons"] = "Disable Addons"
--[[Translation missing --]]
L["Disable addons from the profile '${profile}'?"] = "Disable addons from the profile '${profile}'?"
L["Disable this and every AddOn that depends on it"] = "Dieses Addon und alle davon abhängigen Addons deaktivieren"
L["Disabled Addons"] = "Addons deaktivieren"
L["Enable Addons"] = "Addons aktivieren"
L["Enable addons from the profile '${profile}'?"] = "Addons von Profil '${profile}' aktivieren?"
L["Enable this Addon and its dependencies"] = "Dieses Addon und seine Abhängigkeiten aktivieren"
L["Enable this and every AddOn that depends on it"] = "Dieses Addon und alle davon abhängigen Addons aktivieren"
L["Enabled Addons"] = "Aktivierte Addons"
--[[Translation missing --]]
L["Enabled for all characters"] = "Enabled for all characters"
--[[Translation missing --]]
L["Encounter"] = "Encounter"
--[[Translation missing --]]
L["Encounter CPU: "] = "Encounter CPU: "
L["Enter the category name"] = "Kategorienamen eingeben"
L["Enter the name for the new profile"] = "Namen für neues Profil eingeben"
L["Enter the new name for the category '${category}'"] = "Neuen Namen für Kategorie '${category}' eingeben"
L["Enter the new name for the profile "] = "Neuen Namen für das Profil eingeben"
L["Expand all"] = "Alle ausklappen"
--[[Translation missing --]]
L["Export"] = "Export"
--[[Translation missing --]]
L["Export text"] = "Export text"
L["Fixed category"] = "Fixierte Kategorie"
L["Hide autogenerated categories"] = "Automatisch generierte Kategorien verstecken"
--[[Translation missing --]]
L["Hide icons"] = "Hide icons"
--[[Translation missing --]]
L["Hold shift to add/remove AddOns that depends on it as well"] = "Hold shift to add/remove AddOns that depends on it as well"
--[[Translation missing --]]
L["Hold shift to show all"] = "Hold shift to show all"
L["Ignore addons included in dependent profiles."] = "Addons in abhängigen Profilen ignorieren"
--[[Translation missing --]]
L["Import"] = "Import"
--[[Translation missing --]]
L["Instance Profile"] = "Instance Profile"
L["Internal name"] = "Interner Name"
L["Left-click to open"] = "Linksklick zum öffnen"
L["List Options"] = "Optionen anzeigen"
L["Load"] = "Laden"
L["Load AddOn"] = "Addon laden"
L["Load Profile"] = "Profil laden"
L["Load profile '${profile}' and reload UI?"] = "Profil '${profile}' laden und UI neu laden?"
L["Load the AddOns from '${char}'?"] = "Addons von Charakter '${char}' laden?"
L["Load the profile '${profile}'?"] = "Profil '${profile}' laden?"
L["Localize autogenerated categories name"] = "Automatisch erstelle Kategorien übersetzen"
--[[Translation missing --]]
L["Lock Addon"] = "Lock Addon"
--[[Translation missing --]]
L["Locked Addons"] = "Locked Addons"
L["Manually added:"] = "Manuell hinzugefügt:"
L["Memory Update"] = "Speicher-Aktualisierungszeit"
L["Memory: "] = "Speicher:"
L["Name (improved)"] = "Name (verberssert)"
L["New Category"] = "Neue Kategorie"
L["None"] = "Nichts"
L["Not Found!"] = "Nicht gefunden!"
L["Options"] = "Optionen"
--[[Translation missing --]]
L["Outside"] = "Outside"
--[[Translation missing --]]
L["Party"] = "Party"
--[[Translation missing --]]
L["Paste the exported text here to import it"] = "Paste the exported text here to import it"
--[[Translation missing --]]
L["Peak"] = "Peak"
--[[Translation missing --]]
L["Peak CPU: "] = "Peak CPU: "
L["Profile dependencies"] = "Profilabhängigkeiten"
L["Profiles"] = "Profile"
--[[Translation missing --]]
L["Profiles: "] = "Profiles: "
--[[Translation missing --]]
L["PvP"] = "PvP"
--[[Translation missing --]]
L["Raid"] = "Raid"
L["Reload UI"] = "UI neu laden"
L["Remove search results from category"] = "Suchergebnisse aus Kategorie entfernen"
L["Rename"] = "Umbenennen"
L["Replace original Addon wow menu button"] = "Original WoW Addon Menü Button ersetzen"
L["Result: ${name}"] = "Ergebnis: ${name}"
L["Results: ${results}"] = "Ergebnisse: ${results}"
L["Right-click to edit"] = "Rechtklick zum bearbeiten"
L["Right-click to show profile menu"] = "Rechtsklick um das Profilmenü anzuzeigen"
L["Save"] = "Speichern"
L["Save (*)"] = "Speichern (*)"
L["Save current addons in profile '${profile}'?"] = "Aktuelle Addons im Profil '${profile}' speichern?"
L["Save current addons, ignoring addons included in dependent profiles, into profile '${profile}'?"] = "Aktuelle Addons in Profil '${profile}' speichern, dabei Addons in abhängigen Profilen ignorieren?"
--[[Translation missing --]]
L["Scenario"] = "Scenario"
L["Search By"] = "Suchen nach"
L[ [=[Search in progress...
Status: enabled: ${enabled}, disabled: ${disabled}
The addon you are looking for has been disabled?]=] ] = [=[Suche läuft...
Status: aktiviert: ${enabled}, deaktiviert: ${disabled}
Ist das gesuchte Addon deaktiviert?]=]
L["Search Options"] = "Suchoptionen"
L["Select All"] = "Alle auswählen"
L["Select None"] = "Alle abwählen"
--[[Translation missing --]]
L["Show autogenerated categories"] = "Show autogenerated categories"
--[[Translation missing --]]
L["Show autogenerated custom categories (X-Category)"] = "Show autogenerated custom categories (X-Category)"
L["Show Blizzard addons found in dependencies"] = "Blizzard-Addons in Abhängigkeiten anzeigen"
L["Show memory usage in broker/minimap tooltip"] = "Speichernutzung im Broker/Minimap Tooltip anzeigen"
L["Show minimap button"] = "Minimap-Button anzeigen"
L["Show versions in AddOns list"] = "Versionsnummer in Addon-Liste anzeigen"
--[[Translation missing --]]
L["Show warning dialog when a disabled but locked addon is detected"] = "Show warning dialog when a disabled but locked addon is detected"
--[[Translation missing --]]
L["Some locked addons had to be re-enabled during login. Do you want to reload UI to apply?"] = "Some locked addons had to be re-enabled during login. Do you want to reload UI to apply?"
L["Sort by"] = "Sortieren nach"
L[ [=[Start binary search?
Make sure to save your profile first, just in case.]=] ] = [=[Binary-Suche starten?
Stelle sicher dein Profil zuerst zu speichern.]=]
L["This addons is not installed!"] = "Dieses Addon ist nicht installiert"
--[[Translation missing --]]
L["Tip: You can also alt-click the addon in the list to lock/unlock it"] = "Tip: You can also alt-click the addon in the list to lock/unlock it"
L["Title"] = "Titel"
L["Uncategorized Addons"] = "Unkategorisierte Addons"
L["Update only when opening the main window"] = "Nur beim öffnen des Hauptfensters aktualisieren"
L["User created category"] = "Vom Nutzer erstellte Kategorie"
L["Utilities"] = "Dienstprogramme"
L["Version: "] = "Version:"
L["View AddOn list as dependency tree"] = "Abhängigkeiten von Addons anzeigen (Baumstruktur)"
L["Your AddOns were restored, reload UI?"] = "Deine Addons wurden wiederhergestellt, UI neu laden?"

